[package]
name = "marker"
version = "0.4.0-dev"
authors = ["Alex Crawford <alex.crawford@coreos.com>"]
description = "Tool for finding issues in CommonMark documents"
repository = "https://github.com/crawford/marker"
readme = "README.md"
keywords = ["commonmark", "markdown", "links", "validate"]
license = "Apache-2.0"

[dependencies]
clap = "^2.25.0"
hyper = "^0.10.12"
hyper-rustls = "^0.6.1"
pulldown-cmark = "^0.0.15"
rayon = "^0.8.1"
url = "^1.5.1"
walkdir = "^1.0.7"
