[package]
name = "marker"
version = "0.4.0"
authors = ["Alex Crawford <alex.crawford@coreos.com>"]
description = "Tool for finding issues in CommonMark documents"
repository = "https://github.com/crawford/marker"
readme = "README.md"
keywords = ["commonmark", "markdown", "links", "validate"]
license = "Apache-2.0"

[dependencies]
clap = "^2.20.3"
hyper = "^0.10.4"
hyper-rustls = "^0.3.1"
pulldown-cmark = "^0.0.8"
url = "^1.4.0"
walkdir = "^1.0.7"
rayon= "^0.6.0"
